### ISSUE TITLE
mabel avanglers infinit pet battle

### ISSUE THREAD

**Issue by PBJF** [ELECTR0ZED/Shibe-Bot#14]
I started a pet battle with Rubber Duck Shobe in Shibe Hotel. .pet battle both of us and we were set. until...
HoW dO i TeLl My PeT wHaT tO dO?
Exactly. How to attack? How to cancel? How to defend?
Tried .pet battle again.
"You already are in a battle."
So I guess this is an infinite battle? (title)

**Comment by ELECTR0ZED** [comment]
Battles are not finished yet as it says on the help menu.

**Comment by PBJF** [comment]
Then why are they available?

**Comment by ELECTR0ZED** [comment]
Don't you want a preview of what is to come?

**Comment by PBJF** [comment]
I want a ~~working~~ borking one. JUST USE THE DEFAULT EMOJIS

**Comment by ELECTR0ZED** [comment]
I already decided that last week and the production has started although it is a large project.
