### ISSUE TITLE
Suggestions: Food Items, working, Petcare and grooming

### ISSUE THREAD

**Issue by RubberDuckShobe** [ELECTR0ZED/Shibe-Bot#4]
There should be a work command to earn Shibe Coins every 12h or 24h and buyable food items to level up shibes, the function to groom your shibes (for level-ups) and maybe the function to give your shibe to a pet care that will feed and groom it automatically when needed but will cost a certain amount of shibe coins per day.

**Comment by ELECTR0ZED** [comment]
A daily command will be added but it won't be easy to get the Shibe Bucks, there will be a twist. Buyable food may be released in a future rewrite but not currently. The pet grooming will be considered and the day care will be added but with a different name. Pet exercising may be added to help level them up while battling is in development. Thanks for the suggestion.

**Comment by ELECTR0ZED** [comment]
This has been added to the bot.

**Comment by PBJF** [comment]
Shibe Bucks for beta only... 😐
