### ISSUE TITLE
Unable to purchase Premium

### ISSUE THREAD

**Issue by PBJF** [ELECTR0ZED/Shibe-Bot#8]
Today I got a legendary pet, sold it and got cash to buy premium. I purchased extra bank space and did /buy Premium, but "the item does not exist". Also what about dog toys for pets to increase their XP?

**Comment by k1rbster** [comment]
The commanf /buy 1. It costs 250 Shibe Bucks and you need to click the ✔️ underneath.

**Comment by ELECTR0ZED** [comment]
The suggestion in this was added you can now /buy premium
